site_name: Global Data Barometer Handbook
theme:
  name: material
plugins:
  - search
  - macros:
      include_dir: docs/includes
  - print-site
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - https://hypothes.is/embed.js
extra_css:
  - custom.css