site_name: Global Data Barometer Handbook
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  palette:
    primary: cyan
  logo: img/gdb-5.png
plugins:
  - search
  - literate-nav:
      nav_file: menu.md
  - macros:
      include_dir: docs/includes
  - pdf-export
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
extra_javascript:
  - ga.js
extra_css:
  - custom.css
